version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.13.6
    working_directory: /go/src/github.com/r-anime/ZeroTsu
    steps:
      - checkout
      - run: go get -v -t -d ./...
      - run: go test -v ./...
      - store_test_results:
          path: /tmp/test-results
  deploy:
    machine:
      enabled: true
    steps:
      - run:
          name: Deploy to Server as Service (SSH)
          command: |
            ssh $SSH_USER@$SSH_IP "export GOPATH=/home/apiks/go; sudo systemctl stop zerotsu.service; cd /home/apiks/go/src/github.com/r-anime/ZeroTsu; cp config.json config.json.local; git checkout -- config.json; git pull; /snap/bin/go get -u ./...; cp config.json.local config.json; /snap/bin/go build -o ZeroTsu; sudo systemctl start zerotsu.service"
workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master
